In [ ]:
import torch

Example 1

In [ ]:
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y=x**2

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

Example 2

In [ ]:
x=torch.tensor(4.0,requires_grad=True)
x

tensor(4., requires_grad=True)

In [ ]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
z=torch.sin(y)
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-7.6613)

In [ ]:
y.grad

<ipython-input-30-10b3a7061f6d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


Gradient of middle value is not calculated by this method         
but we can do it by another method.

# Training a neural network with autograd

In [ ]:
import torch

x=torch.tensor(6.7) #cgpa of student
y=torch.tensor(0.0) #placed

w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [ ]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy(y_pred,y_true):
  epsilon = 1e-8  # To prevent log(0)
  prediction=torch.clamp(y_pred,epsilon,1-epsilon)
  return -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))

In [ ]:
# Forward pass
z=w*x+b
y_pred=torch.sigmoid(z)

# Compute binary cross-entropy loss
loss=binary_cross_entropy(y_pred,y)

# loss
z,y_pred,loss

(tensor(6.7000, grad_fn=<AddBackward0>),
 tensor(0.9988, grad_fn=<SigmoidBackward0>),
 tensor(6.7012, grad_fn=<NegBackward0>))

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

#Multi-dimension Tensors

In [ ]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y=x**2
y

tensor([1., 4., 9.], grad_fn=<PowBackward0>)

In [ ]:
z=y.mean()
z

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

# Clearing gradient data
we need to clear x.grad

if do not clear it next value of grad will add in it of the next pass

In [ ]:
x.grad.zero_()

tensor([0., 0., 0.])

# Disable Gradient Tracking
At the inference time their is no need for autograd and it also is time tacking and memory taking process so we need to disable it.

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
x.grad

In [ ]:
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [ ]:
x.requires_grad_(False)
x

tensor(2.)

In [ ]:
y = x ** 2

In [ ]:
y

tensor(4.)

In [ ]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
z=x.detach()
z

tensor(2.)

In [ ]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y0=z**2
y0

tensor(4.)

In [ ]:
y.backward()

In [ ]:
y0.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn