In [8]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available")

CUDA is not available


## Creating a Tensor

In [ ]:
# using empty
a=torch.empty(2,3)
print(a)

tensor([[-2.6874e-10,  4.3592e-41,  6.9642e-19],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# check data type
a.dtype

torch.float32

In [ ]:
# using zeros
b=torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.0833, 0.6552, 0.8312],
        [0.8081, 0.8667, 0.3695]])

In [ ]:

torch.rand(2,3)

tensor([[0.2572, 0.1944, 0.9552],
        [0.4389, 0.9376, 0.8867]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# arange
torch.arange(2,20,1)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# using linspace
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [ ]:
# using eye
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# using full
torch.full((3,3),1)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x.shape

torch.Size([3, 3])

In [ ]:
torch.empty_like(x)

tensor([[133610788339088,       682848064,       683004384],
        [      680117056,               0,       681026336],
        [      620990864, 133606160412656,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=torch.int)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
# using to()
x.to(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x.to(torch.double)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.4235, 0.0169],
        [0.2209, 0.9535]])

In [ ]:
# addition
x+2

tensor([[2.4235, 2.0169],
        [2.2209, 2.9535]])

In [ ]:
# substraction
x-2

tensor([[-1.5765, -1.9831],
        [-1.7791, -1.0465]])

In [ ]:
# multiplication
x*2

tensor([[0.8470, 0.0338],
        [0.4418, 1.9071]])

In [ ]:
# division
x/2

tensor([[0.2117, 0.0084],
        [0.1104, 0.4768]])

In [ ]:
# mod
x%2

tensor([[0.4235, 0.0169],
        [0.2209, 0.9535]])

In [ ]:
# power
x**2

tensor([[1.7934e-01, 2.8558e-04],
        [4.8794e-02, 9.0923e-01]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7064, 0.1629, 0.8902],
        [0.5163, 0.0359, 0.6476]])
tensor([[0.3430, 0.3182, 0.5261],
        [0.0447, 0.5123, 0.9051]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0204, 0.1629, 0.3641],
        [0.0250, 0.0359, 0.6476]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
c.neg()

tensor([-1,  2, -3,  4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
d.round()

tensor([2., 2., 4., 4.])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [27]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float64)
e

tensor([[4., 6., 7.],
        [1., 6., 4.]], dtype=torch.float64)

In [10]:
# sum
torch.sum(e)

tensor(22., dtype=torch.float64)

In [11]:
# sum along columns
torch.sum(e, dim=0)

tensor([6., 8., 8.], dtype=torch.float64)

In [12]:
# sum along rows
torch.sum(e, dim=1)

tensor([18.,  4.], dtype=torch.float64)

In [13]:
# mean
torch.mean(e)

tensor(3.6667, dtype=torch.float64)

In [14]:
# mean along col
torch.mean(e, dim=0)

tensor([3., 4., 4.], dtype=torch.float64)

In [15]:
# mean along row
torch.mean(e,dim=1)

tensor([6.0000, 1.3333], dtype=torch.float64)

In [16]:
# median
torch.median(e)

tensor(4., dtype=torch.float64)

In [17]:
# median along row
torch.median(e,dim=1)

torch.return_types.median(
values=tensor([6., 0.], dtype=torch.float64),
indices=tensor([0, 1]))

In [18]:
# median along column
torch.median(e,dim=0)

torch.return_types.median(
values=tensor([0., 0., 4.], dtype=torch.float64),
indices=tensor([1, 1, 0]))

In [20]:
# max and min
torch.max(e),torch.min(e)

(tensor(8., dtype=torch.float64), tensor(0., dtype=torch.float64))

In [23]:
# product
torch.prod(e)

tensor(142884., dtype=torch.float64)

In [24]:
# standard deviation
torch.std(e)

tensor(1.9748, dtype=torch.float64)

In [25]:
# variance
torch.var(e)

tensor(3.9000, dtype=torch.float64)

In [28]:
# argmax
torch.argmax(e)

tensor(2)

In [29]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [31]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [32]:
f,g

(tensor([[8, 2, 8],
         [9, 2, 6]]),
 tensor([[9, 8],
         [6, 8],
         [8, 2]]))

In [33]:
# matrix multiplcation
torch.matmul(f,g)

tensor([[148,  96],
        [141, 100]])

In [34]:
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([4,5,6])

dot_product=torch.dot(vector1,vector2)
dot_product

tensor(32)

In [38]:
# transpose
torch.transpose(f,0,1)

tensor([[8, 9],
        [2, 2],
        [8, 6]])

In [39]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 1., 1.],
        [3., 5., 8.],
        [9., 1., 6.]])

In [40]:
# determinant
torch.det(h)

tensor(122.)

In [41]:
# inverse
torch.inverse(h)

tensor([[ 0.1803, -0.0410,  0.0246],
        [ 0.4426,  0.1721, -0.3033],
        [-0.3443,  0.0328,  0.1803]])

### 5. Comparison operations

In [42]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 9, 4],
        [4, 3, 3]])
tensor([[5, 7, 6],
        [8, 8, 5]])


In [43]:
# greater than
i>j

tensor([[False,  True, False],
        [False, False, False]])

In [44]:
# less than
i<j

tensor([[False, False,  True],
        [ True,  True,  True]])

In [45]:
# equal to
i==j

tensor([[ True, False, False],
        [False, False, False]])

In [46]:
# not equal to
i!=j

tensor([[False,  True,  True],
        [ True,  True,  True]])

In [47]:
# greater than equal to
i>=j

tensor([[ True,  True, False],
        [False, False, False]])

In [48]:
# less than equal to
i<=j

tensor([[ True, False,  True],
        [ True,  True,  True]])

### 6. Special functions

In [51]:
  k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float64)
  k

tensor([[2., 1., 3.],
        [3., 4., 6.]], dtype=torch.float64)

In [52]:
# log
torch.log(k)

tensor([[0.6931, 0.0000, 1.0986],
        [1.0986, 1.3863, 1.7918]], dtype=torch.float64)

In [53]:
# exp
torch.exp(k)

tensor([[  7.3891,   2.7183,  20.0855],
        [ 20.0855,  54.5982, 403.4288]], dtype=torch.float64)

In [54]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 1.0000, 1.7321],
        [1.7321, 2.0000, 2.4495]], dtype=torch.float64)

In [55]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.7311, 0.9526],
        [0.9526, 0.9820, 0.9975]], dtype=torch.float64)

In [56]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.2689, 0.0474, 0.0474],
        [0.7311, 0.9526, 0.9526]], dtype=torch.float64)

In [57]:
# relu
torch.relu(k)

tensor([[2., 1., 3.],
        [3., 4., 6.]], dtype=torch.float64)

## Inplace Operations

In [58]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.2501, 0.1390, 0.8565],
        [0.6578, 0.3946, 0.6180]])
tensor([[0.2707, 0.7570, 0.2641],
        [0.4532, 0.4441, 0.7297]])


In [60]:
m.add_(n)

tensor([[0.5209, 0.8960, 1.1206],
        [1.1110, 0.8387, 1.3477]])

In [61]:
m

tensor([[0.5209, 0.8960, 1.1206],
        [1.1110, 0.8387, 1.3477]])

In [62]:
n

tensor([[0.2707, 0.7570, 0.2641],
        [0.4532, 0.4441, 0.7297]])

In [63]:
torch.relu(m)

tensor([[0.5209, 0.8960, 1.1206],
        [1.1110, 0.8387, 1.3477]])

In [64]:
m.relu_()

tensor([[0.5209, 0.8960, 1.1206],
        [1.1110, 0.8387, 1.3477]])

In [65]:
m

tensor([[0.5209, 0.8960, 1.1206],
        [1.1110, 0.8387, 1.3477]])

## Copying a Tensor

In [66]:
a = torch.rand(2,3)
a

tensor([[0.4025, 0.7497, 0.5580],
        [0.9568, 0.5850, 0.9148]])

In [67]:
b=a

In [69]:
b

tensor([[0.4025, 0.7497, 0.5580],
        [0.9568, 0.5850, 0.9148]])

In [70]:
a[0]=24

In [72]:
a,b

(tensor([[24.0000, 24.0000, 24.0000],
         [ 0.9568,  0.5850,  0.9148]]),
 tensor([[24.0000, 24.0000, 24.0000],
         [ 0.9568,  0.5850,  0.9148]]))

In [73]:
id(a),id(b)

(135598930145072, 135598930145072)

In [74]:
b=a.clone()

In [75]:
id(a),id(b)

(135598930145072, 135598747718800)